---
originRequest:
  originServerName: external.hypyr.space

ingress:
  - hostname: hypyr.space
    service: https://nginx-external-controller.networking.svc.cluster.local
  - hostname: "*.hypyr.space"
    service: https://nginx-external-controller.networking.svc.cluster.local
  - service: http_status:404
