---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: github
spec:
  type: github
  address: https://github.com/cpritchett/homelab-cluster
  secretRef:
    name: github-token-secret
